# Generated by Django 5.2.8 on 2025-11-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=100)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='posts/')),
                ('mensagem', models.TextField()),
            ],
        ),
    ]
